name: hap_dart
description: A HomeKit Accessory Protocol (HAP) implementation in Dart for Linux.
version: 1.0.0
repository: https://github.com/fingersonfire/HAP-dart
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  crypto: ^3.0.5
  cryptography: ^2.7.0
  dbus: ^0.7.10
  meta: ^1.16.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
